name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Caching
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install
      run: npm install
    - name: Build
      run: npm run build --if-present
    - name: Unit Tests
      run: npm run test:unit
      env:
        CI: true
    - name: Cypress run
      uses: cypress-io/github-action@v1
      with:
        start: npm run serve
        wait-on: http://localhost:8080/
        config_file: cypress.json
        spec: "tests/e2e/**/*"
      env:
        CYPRESS_baseUrl: http://localhost:8080/

