name: Node.js CI on master

on:
  push:
    branches:
    - master
    paths-ignore:
    - '.github/workflows'

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/$GITHUB_REPOSITORY/actions-showcase:$GITHUB_SHA
    - name: Publish to GitHub Package Registry
      env:
        DOCKER_TOKEN: ${{secrets.GITHUB_TOKEN}}
        DOCKER_USER: <token>
      run: |
        docker login docker.pkg.github.com -u $DOCKER_USER -p $DOCKER_TOKEN
        docker push docker.pkg.github.com/$GITHUB_REPOSITORY/actions-showcase:$GITHUB_SHA