name: Cleanup

on:
  pull_request:
    types: [closed]

jobs:

  clean:
    name: Cleanup Review apps
    runs-on: ubuntu-latest

    steps:
    - name: Checking out the code
      uses: actions/checkout@v2
    - uses: actions/github-script@0.8.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          console.log(context)
          console.log(context.pull_request.base)
          github.repos.listDeployments({
            owner: context.repo.owner,
            repo: context.repo.repo
          }).then(deployments => {
            console.log(deployments)
          })
          