name: Click

on: [repository_dispatch]


jobs:
  doSomething:
    runs-on: ubuntu-latest
    steps:
    - run: |
      export MyVar=Hello
      echo "Hello world"
      echo "::set-env name=MyMessage::$MyVar"
    - run: echo $MyMessage