name: Deploy a review app on Azure

on:
  deployment

jobs:

  update_status:
    name: Status update
    if: github.event.deployment.environment == 'test'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@0.8.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          let run = process.env.GITHUB_RUN_ID
          let log_url = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${run}`
          github.repos.createDeploymentStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            mediaType: {
              previews: ["flash-preview", "ant_man"]
            },
            deployment_id: context.payload.deployment.id,
            state: 'in_progress',
            description: 'Deployment from GitHub Actions started', 
            log_url: log_url
          })
  
  container:
    name: Build & publish container
    needs: update_status
    runs-on: ubuntu-latest
    steps:
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/$GITHUB_REPOSITORY/actions-showcase:$GITHUB_SHA
    - name: Publish to GitHub Package Registry
      env:
        DOCKER_TOKEN: ${{secrets.GITHUB_TOKEN}}
        DOCKER_USER: <token>
      run: |
        docker login docker.pkg.github.com -u $DOCKER_USER -p $DOCKER_TOKEN
        docker push docker.pkg.github.com/$GITHUB_REPOSITORY/actions-showcase:$GITHUB_SHA
  
  azure_app:
    name: Create the review app on Azure
    needs: update_status
    runs-on: ubuntu-latest
    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Create the review app
      env:
        RESOURCE_GROUP: bookstore
        APP_SERVICE_PLAN: bookstore-app-service-plan
        WEBAPP_NAME_PREFIX: actions-showcase
        DOCKER_REGISTRY_URL: docker.pkg.github.com
      run: |
        az webapp create --resource-group $RESOURCE_GROUP --plan $APP_SERVICE_PLAN --name $WEBAPP_NAME_PREFIX-$GITHUB_SHA --deployment-container-image-name docker.pkg.github.com/$GITHUB_REPOSITORY/$WEBAPP_NAME_PREFIX:$GITHUB_SHA
        az webapp config container set --resource-group $RESOURCE_GROUP --name $WEBAPP_NAME_PREFIX-$GITHUB_SHA --docker-registry-server-url $DOCKER_REGISTRY_URL
        az webapp update -g $RESOURCE_GROUP -n $WEBAPP_NAME_PREFIX-$GITHUB_SHA --set tags.ref=$GITHUB_REF tags.type=review


