name: Deploy a review app on Azure

on:
  deployment

jobs:

  deploy:
    name: Deploy
    if: github.event.deployment.environment == 'test'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/github-script@0.8.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          let run = process.env.GITHUB_RUN_ID
          let log_url = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${run}`
          github.repos.createDeploymentStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            mediaType: {
              previews: ["flash-preview", "ant_man"]
            },
            deployment_id: context.payload.deployment.id,
            state: 'in_progress',
            log_url: log_url
          })

          