name: Deploy a review app on Azure

on:
  deployment

jobs:

  deploy:
    name: Deploy
    if: github.event.deployment.environment == 'test'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
      echo "::warning::${{toJson(github.event)}}"
      echo "::set-env name=log_url::`https://github.com/{github.repository}/actions/runs/{github.run_id}`}}"
    - uses: actions/github-script@0.8.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          console.log(process.env)
          github.repos.createDeploymentStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            mediaType: {
              previews: ["flash-preview", "ant_man"]
            },
            deployment_id: context.payload.deployment.id,
            state: 'in_progress',
            log_url: ${{format('https://github.com/{0}/actions/runs/{1}', github.repository, github.run_id)}}"
          })

          