name: Deploy a review app on Azure

on:
  deployment

jobs:

  deploy:
    name: Deploy
    if: github.event.deployment.environment == 'test'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: echo "::warning::${{github.event}}"
    - uses: actions/github-script@0.8.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.repos.createDeploymentStatus({
            'helaili',
            'actions-showcase',
            5,
            'Deploying to test'
          })